[package]
name = "cmdtaglib"
version = "0.1.2"
authors = ["Czipperz <czipperz@gmail.com>"]
description = "A command line application that allows you to interact with `tablib`"
keywords = ["taglib", "tag", "tags", "metadata", "media"]
license = "Unlicense"

[dependencies]
taglib = "0.1.0"
